name: "Build and populate cache"
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ contains(matrix.system, 'darwin') && 'macos-latest' || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - system: x86_64-linux
          - system: aarch64-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup cachix
        uses: cachix/cachix-action@v16
        with:
          name: derethil
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build neovim configuration
        run: nix build .#packages.${{ matrix.system }}.default

